name: coronavirus
description: A new way to track corona virus

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Better with dart
  http: ^0.12.0+4
  rxdart: ^0.18.0
  intl: ^0.16.1

  # Open url or something like that ec. mail
  url_launcher: ^5.4.2

  # Charts
  charts_flutter: ^0.9.0
  
  # UI Packages
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.3+1
  font_awesome_flutter: ^8.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - graphics/